In [126]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris

In [127]:
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [128]:
iris.keys()

dict_keys(['target_names', 'filename', 'data', 'DESCR', 'target', 'feature_names'])

In [129]:
X = iris.data 
y = iris.target

In [130]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [131]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [132]:
from sklearn.model_selection import train_test_split




In [133]:
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size= 0.3 , random_state=999)

In [134]:

from sklearn.preprocessing import StandardScaler




In [135]:
scaler = StandardScaler() # 이걸 왜해주는거지?   
# standardScaler : 각 특성의 평균을 0, 분산을 1로 변경하여 특성의 스케일을 맞춥니다.
# 최솟값과 최댓값의 크기를 제한하지 않습니다.
# x−x¯σ

In [136]:
scaler.fit(X_train)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [137]:
X_train=scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [138]:
from sklearn.neighbors import KNeighborsClassifier

In [139]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train) #KNN은 사전교육이 필요 없음 이 fit 은 좌표만 알려줌 


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [125]:
y_pred = model.predict(X_test)

In [103]:
#confuse matrix 
#classfication report 

In [110]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics


conMat = pd.DataFrame(confusion_matrix(y_test,y_pred))
conMat

0   1   2
0  14   1   0
1   0  11   1
2   0   1  17

In [105]:
print(metrics.classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.85      0.92      0.88        12
           2       0.94      0.94      0.94        18

   micro avg       0.93      0.93      0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45



In [106]:
new_sample = iris.data[3]

In [107]:
new_sample = scaler.transform([new_sample])

In [108]:
model.predict(new_sample)

array([0])

In [109]:
X_train[3]

array([-0.88211998,  1.68320594, -1.27063979, -1.17577606])